#%RAML 1.0
title: MUJIN Controller API
version: v1
baseUri: http://controller

traits:
  secured:
    headers:
      Authorization:
        example: Basic bXVqaW46bXVqaW4=
        required: true

types:
  Meta:
    type: object
    properties:
      total_count: integer
      limit: integer
      offset: integer
      previous?: string
      next?: string
  SystemInfo:
    type: object
    properties:
      hardware: string
      product: string
      id: string
  SystemStats:
    type: object
    properties:
      memory: object
      disk: object
      temperature: array
      cpu: object
  DebugResource:
    type: object
    properties:
      pk: string
      resource_uri: string
      description: string
      name: string
      downloadUri: string
      datemodified: string
      unit: string
      size: integer


/systeminfo/:
  is: [secured]
  get:
    responses:
      200:
        body:
          application/json:
            type: SystemInfo
            example: |
              {
                "hardware": "HARDWARE-MODEL",
                "product": "PRODUCT-ID",
                "id": "controller"
              }

/systemstats/:
  is: [secured]
  get:
    responses:
      200:
        body:
          application/json:
            type: SystemStats


/api/{version}/debug:
  is: [secured]
  /:
    get:
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                objects: DebugResource[]
                meta: Meta
              example: |
                {
                  "objects": [],
                  "meta": {
                    "total_count": 0,
                    "limit": 20,
                    "offset": 0
                  }
                }
    post:
      responses:
        201:
          body:
            application/json:
              type: DebugResource
  /{pk}/:
    get:
      responses:
        200:
          body:
            application/json:
              type: DebugResource
    delete:
      responses:
        204:
    put:
      responses:
        202:
          body:
            application/json:
              type: DebugResource
