#%RAML 1.0 Overlay
masterRef: api.raml
title: MUJIN コントローラ

types:
  Meta:
    displayName: 共用メタデータ
  SystemInfo:
    properties:
      product:
        description: 製品番号
      hardware:
        description: ハードウェア識別
      id:
        description: コントローラ識別

/systeminfo/:
  displayName: システムインフォメーション
  get:
    displayName: システム情報を取得

/systemstats/:
  displayName: システム統計
  get:
    displayName: システム統計を取得

/api/{version}/debug:
  displayName: デバッグ
  description: デバッグログを取得
