#%RAML 1.0 Overlay
masterRef: api.raml
title: MUJIN Controller API

traits:
  secured:
    headers:
      Authorization:
        description: Authorization credentials

types:
  Meta:
    displayName: Common Metadata
  SystemInfo:
    displayName: System Information
  SystemStats:
    displayName: System Statistics
  DebugResource:
    displayName: Debug Resource

/systeminfo/:
  displayName: System Information
  get:
    displayName: Get System Information

/systemstats/:
  displayName: System Statistics
  get:
    displayName: Get System Statistics
