#%RAML 1.0 Library

types:
  SystemInfo:
    type: object
    displayName: System Information
    properties:
      hardware: string
      product: string
      id: string
  SystemStats:
    type: object
    displayName: System Statistics
    properties:
      memory: object
      disk: object
      temperature: array
      cpu: object
