#%RAML 1.0 Library

types:
  DebugResource:
    type: object
    properties:
      description: string
      name: string
      downloadUri: string
      pk: string
      resource_uri: string
      datemodified: string
      unit: string
      size: string
