#%RAML 1.0 Library

types:
  SceneResource: !include ../schemas/scene.schema
  ObjectResource: !include ../schemas/object.schema
  RobotResource: !include ../schemas/robot.schema
  LinkResource: !include ../schemas/link.schema
  AttachmentResource: !include ../schemas/attachment.schema
  GeometryResource: !include ../schemas/geometry.schema
  AttachedSensorResource: !include ../schemas/attachedsensor.schema
  IkParamResource: !include ../schemas/ikparam.schema
  GraspsetResource: !include ../schemas/graspset.schema
  InstObjectResource: !include ../schemas/instobject.schema
  InstObjectToolResource: !include ../schemas/instobjecttool.schema