name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g raml2html@7.5.0 raml2html-slate-theme@2.6.0
    - run: mkdir ./build
    - run: raml2html --theme raml2html-slate-theme --input api.raml --output ./build/index.html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

